import type { RacerPerformance } from '../types/sg';

// モック選手成績データ
export function getMockRacerPerformances(): RacerPerformance[] {
  return [
    {
      racerId: '4444',
      name: '桐生順平',
      branch: '埼玉',
      rank: 'A1',
      winRate: 8.56,
      avgStartTiming: 0.14,
      sgWins: 12,
      g1Wins: 28,
      g2Wins: 15,
      generalWins: 45,
      totalPrizeMoney: 25800,
      prizeRanking: 1,
      sgAppearances: 48,
      sgFinalAppearances: 35,
      sgPoints: 245,
      g2PlusPoints: 142,
      g2PlusFinalPoints: 1250,
      fanVotes: 45000,
      fanVoteRank: 1,
      periodWinRate: 8.56,
      raceAppearances: 185
    },
    {
      racerId: '4320',
      name: '峰竜太',
      branch: '佐賀',
      rank: 'A1',
      winRate: 8.42,
      avgStartTiming: 0.15,
      sgWins: 10,
      g1Wins: 32,
      g2Wins: 18,
      generalWins: 52,
      totalPrizeMoney: 23400,
      prizeRanking: 2,
      sgAppearances: 52,
      sgFinalAppearances: 38,
      sgPoints: 238,
      g2PlusPoints: 138,
      g2PlusFinalPoints: 1180,
      fanVotes: 42000,
      fanVoteRank: 2,
      periodWinRate: 8.42,
      raceAppearances: 190
    },
    {
      racerId: '3960',
      name: '茅原悠紀',
      branch: '岡山',
      rank: 'A1',
      winRate: 8.28,
      avgStartTiming: 0.16,
      sgWins: 5,
      g1Wins: 22,
      g2Wins: 14,
      generalWins: 38,
      totalPrizeMoney: 19200,
      prizeRanking: 3,
      sgAppearances: 42,
      sgFinalAppearances: 28,
      sgPoints: 210,
      g2PlusPoints: 125,
      g2PlusFinalPoints: 1050,
      fanVotes: 35000,
      fanVoteRank: 3,
      periodWinRate: 8.28,
      raceAppearances: 180
    },
    {
      racerId: '4166',
      name: '毒島誠',
      branch: '群馬',
      rank: 'A1',
      winRate: 8.15,
      avgStartTiming: 0.15,
      sgWins: 8,
      g1Wins: 25,
      g2Wins: 16,
      generalWins: 42,
      totalPrizeMoney: 18500,
      prizeRanking: 4,
      sgAppearances: 45,
      sgFinalAppearances: 32,
      sgPoints: 220,
      g2PlusPoints: 130,
      g2PlusFinalPoints: 1120,
      fanVotes: 38000,
      fanVoteRank: 4,
      periodWinRate: 8.15,
      raceAppearances: 182
    },
    {
      racerId: '4024',
      name: '池田浩二',
      branch: '愛知',
      rank: 'A1',
      winRate: 8.05,
      avgStartTiming: 0.16,
      sgWins: 11,
      g1Wins: 30,
      g2Wins: 20,
      generalWins: 48,
      totalPrizeMoney: 17800,
      prizeRanking: 5,
      sgAppearances: 50,
      sgFinalAppearances: 36,
      sgPoints: 232,
      g2PlusPoints: 135,
      g2PlusFinalPoints: 1150,
      fanVotes: 40000,
      fanVoteRank: 5,
      periodWinRate: 8.05,
      raceAppearances: 188
    },
    // 以下、6位～70位までの選手データ（簡略版）
    ...Array.from({ length: 65 }, (_, i) => {
      const rank = i + 6;
      const isA1 = rank <= 52;
      const baseWinRate = 7.8 - (rank * 0.02);
      const basePrizeMoney = 17000 - (rank * 200);
      const baseGeneralWins = Math.max(3, 48 - rank);
      
      return {
        racerId: `${5000 + rank}`,
        name: `選手${rank}`,
        branch: ['東京', '大阪', '福岡', '愛知', '広島', '静岡'][rank % 6],
        rank: isA1 ? 'A1' : rank <= 60 ? 'A2' : 'B1',
        winRate: Math.max(5.5, baseWinRate),
        avgStartTiming: 0.15 + (rank * 0.001),
        sgWins: Math.max(0, 12 - Math.floor(rank / 5)),
        g1Wins: Math.max(0, 30 - Math.floor(rank / 2)),
        g2Wins: Math.max(0, 20 - Math.floor(rank / 3)),
        generalWins: baseGeneralWins,
        totalPrizeMoney: Math.max(1000, basePrizeMoney),
        prizeRanking: rank,
        sgAppearances: Math.max(0, 50 - rank),
        sgFinalAppearances: Math.max(0, 36 - rank),
        sgPoints: Math.max(0, 230 - (rank * 3)),
        g2PlusPoints: Math.max(0, 134 - (rank * 2)),
        g2PlusFinalPoints: Math.max(0, 1140 - (rank * 15)),
        fanVotes: isA1 ? Math.max(1000, 39000 - (rank * 500)) : 0,
        fanVoteRank: rank,
        periodWinRate: Math.max(5.5, baseWinRate),
        raceAppearances: isA1 ? Math.max(160, 187 - rank) : Math.max(100, 150 - rank)
      } as RacerPerformance;
    })
  ];
}
